version: "3.8"
services:
  data-source:
    build:
      context: ./data-source
    networks:
      - gateway
    environment:
      PORT: "8080"
      REDIS_URL: "redis:6379"
      KAFKA_URL: "kafka:9092"
      PRODUCER_TOPIC: "secret-topic"
      CONSUMER_TOPIC: "cardinfo-topic"
    depends_on:
      - kafka
  data-flow:
    build:
      context: ./data-flow
    networks:
      - gateway
    environment:
      PORT: "8081"
      REDIS_URL: "redis:6379"
      KAFKA_URL: "kafka:9092"
      PRODUCER_TOPIC: "secret-topic"
      CONSUMER_TOPIC: "cardinfo-topic"
    depends_on:
      - redis
      - kafka
  data-proof:
    build:
      context: ./data-proof
    networks:
      - gateway
    environment:
      PORT: "8082"
      REDIS_URL: "redis:6379"
      KAFKA_URL: "kafka:9092"
      CONSUMER_TOPIC: "secret-topic"
    depends_on:
      - redis
      - kafka
  redis:
    image: redis:latest
    networks:
      - gateway
    ports:
      - 6379:6379
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    networks:
      - gateway
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    networks:
      - gateway
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
networks:
  gateway:
    driver: bridge
